Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -21,7 +21,13 @@ jobs:
 
       - name: Trigger Automation Tests
         run: |
-          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
+          response = $(curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            --data '{"event_type": "trigger-automation"}' \
-           https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/dispatches
+           https://api.github.com/repos/Indra512/PlaywrightCucumberJavaScript/dispatches)
+           
+           if [[ "$response" == "" ]]; then
+            echo "Failed to trigger automation workflow!"
+            exit 1
+          fi
+            echo "Automation workflow triggered successfully."
